services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cowchat'
      - 'POSTGRES_PASSWORD=Borman15'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - cowchat:/var/lib/postgresql/data
    networks:
      - cownetwork

volumes:
  cowchat:

networks:
  cownetwork:
    driver: bridge

